repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
    files: \.(md|yml|yaml)$
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]
  - id: trailing-whitespace
    files: \.(md|yml|yaml)$
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.11.2
  hooks:
  - id: markdown-link-check
    args: [--config=.mdc.conf.json]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.35.0
  hooks:
  - id: markdownlint-fix
