name: pre-commit autoupdate

on:
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: browniebroke/pre-commit-autoupdate-action@main
    - shell: bash
      run: echo "START_TIME=$(TZ=":Asia/Tokyo" date +%Y-%m-%d)" >> $GITHUB_ENV
    - uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/pre-commit-hooks-${{ env.START_TIME }}
        title: Update pre-commit hooks (${{ env.START_TIME }})
        commit-message: update pre-commit hooks (${{ env.START_TIME }})
        body: Update versions of pre-commit hooks to latest version.
